   language: python

    python:

      - "3.6.7"


    services: 

      - mysql

    env: 

      -DJANGO=2.1.5 DB=mysql
    install: 

      - pip install -r requirements.txt

    before_script: 

      - mysql -e 'create database test;' -u root
    script: 

      - python3 manage.py test